### ISSUE TITLE
[Feature] Add ULX3S board

### ISSUE THREAD

**Issue by langster1980** [FPGAwars/icestudio#336] opened 2019-09-05 21:21 UTC
I'm using the ULX3S board from the guys at Radiona!  Its a really cool piece of kit and I know you guys got it working with APIO in previous versions.  It would be very nice if this board could be added to Ice studio.

Cheers

Alex

**Comment by drtrigon** [comment] 2019-09-06 20:11
Duplicate of #320

**Comment by Obijuan** [comment] 2019-12-23 10:03
The updates about this issue will be in the #320 
I will close this issue

**Closed by Obijuan** 2019-12-23 10:03 UTC
