### ISSUE TITLE
Windows with Visual Studio Install Issues

### ISSUE THREAD

**Issue by gojimmypi** [FPGAwars/icestudio#368] opened 2019-12-25 09:36 UTC
I'm following up [my tweets](https://twitter.com/gojimmypi/status/1209494050367299586?s=20) with details of some of the problems I encountered during install of icestorm for the ULX3S on Windows 10.

First, it didn't work at all in WSL, I assume as Node version in WSL was 8 and version 12 was needed. `npm start` just sat waiting...

![image](https://user-images.githubusercontent.com/13059545/71441469-6e05d200-26b6-11ea-9c52-adee76f54f55.png)

So then for a regular Windows install, I saw a ton of errors during `npm install`:

![image](https://user-images.githubusercontent.com/13059545/71440365-c5ee0a00-26b1-11ea-8a09-fd0cc5e3c8ab.png)

When I tried to ignore the errors and start icestudio anynow, all I saw was a blank Windows app:

![image](https://user-images.githubusercontent.com/13059545/71440434-ef0e9a80-26b1-11ea-86a7-f957146def1a.png)

I ended up rebooting... and unfortunately then lost the entire install history, so all that is left is that tweet pic for errors :/

After the reboot, a non-blank icestudio seems to have at least launched (I have no idea what underlying problems may exist due to errors during install)... however Python refused to be recognized, despite being able to go to a command prompt and type "python" and get to a python prompt... even after a new fresh install of a more recent Python.

As it turns out, there are a couple of script files such as [toolchain_builder.js](https://github.com/FPGAwars/icestudio/blob/dcbbbb7f9e28fd74b129a3d1ac67e85a3886d58a/tasks/toolchain_builder.js#L279) and [utils.js](https://github.com/FPGAwars/icestudio/blob/dcbbbb7f9e28fd74b129a3d1ac67e85a3886d58a/app/scripts/services/utils.js#L31) that have the `Python.exe` check hard coded like this:

```
    if (process.platform === 'win32') {
      possibleExecutables.push('python.exe');
      possibleExecutables.push('C:\\Python38\\python.exe');
      possibleExecutables.push('C:\\Python37\\python.exe');
      possibleExecutables.push('C:\\Python36\\python.exe');
      possibleExecutables.push('C:\\Python35\\python.exe');
    }
```
However, the Python installer seems to recognize that I have Visual Studio installed, as my Python was in:

```
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64
```
Even when re-installing, the updates did not go to any `C:\Python` directory.

I tried adding this line in hopes of solving this and submitting a PR:

```
      possibleExecutables.push('C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\python.exe');

```
but it was not successful. The icestudio app still did not find Python (which was essential to installing the ECP5 toolchain). I suspect there are more hard-coded path checks in other places.

I don't have Python installed via Visual Studio 2019, 

![image](https://user-images.githubusercontent.com/13059545/71441045-a73d4280-26b4-11ea-933b-3f1a03b8a4c4.png)

but I *do* have it in the side-by-side installed of Visual Studio 2017:

![image](https://user-images.githubusercontent.com/13059545/71441076-d18f0000-26b4-11ea-95f3-678981ff7b28.png)

(note that my Python is installed in the Visual Studio "share" directory)

I resorted to a brute-force solution of copying the contents of my

```
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64
```

to a new directory:

```
C:\Python36\
```

That seemed to resolve the Python issues for installing the toolchain! (yes, it takes some time to download)

As noted in the tweet thread, there were a few other non-intuitive problems, such as the sample code not building, but no error actually displayed in the little red/pink box:

![image](https://user-images.githubusercontent.com/13059545/71441271-b2dd3900-26b5-11ea-877a-35e22124a9c3.png)

@mmicko to the rescue here - I simply needed to change `gn27` to `led[0]` and it *WORKED!* :)

oh - note that the icestudio `Tools-Drivers-Enable` wants to setup the libusbK drivers. I did *not* do this. I have the FTDI drivers installed:

![image](https://user-images.githubusercontent.com/13059545/71441911-6e9f6800-26b8-11ea-9942-79f0242eda01.png)

Having something like icestudio is really amazing, particularly for newbies like me just learning FPGAs. This is also really great for the [ULX3S](https://www.crowdsupply.com/radiona/ulx3s) that I hope to see more widely available soon.

Thank you all that contribute to these open source tools :)

Let me know how I can help. Cheers.

*edits: python installer clarification & add details on FTDI device drivers

**Comment by csylvain** [comment] 2020-01-15 17:18
i installed the libusbK drivers with Zadig as instructed ("Interface 0" only) and the WTFpga board i have would not start up. i eventually ran Zadig again and replaced the windows driver on the second port ("Interface 1") and then the board would start up and both ports appear as "libusbK USB Devices" in devmgmt.msc

**Comment by csylvain** [comment] 2020-01-15 17:20
to install the toolchain, it was necessary for me to run "easy_install -U apio" manually from the directory where 'pip' is found (pip itself would throw an error on start up). having used 'easy_install' then ICEStudio could complete the toolchain installation

**Comment by GnarlyDave** [comment] 2020-04-09 08:24
I'm seeing some similar problems with a windows install and python detection.
I had multiple versions of python and VS installed but python didn't seem to be available. (I don't have %PYTHON% set)
Trying to install node.js and the development environment, suggests that node-gyp needs help to spot python:
CLI> npm config set python <path-to-python...>
find the path by using
 py --list-paths
which I was going to try adding to the nsis installer, and tweak it so it looks for >= python 3.7 versions instead of =3.7

**Comment by cavearr** [comment] 2020-04-09 08:38
Try to download the last nightly version and tell us!

**Comment by GnarlyDave** [comment] 2020-04-09 19:38
uninstall ice studio. uninstall python 2.7 (left 3.8.2 installed)
download nightly win 64
install says python 3.8.2 will be installed. despite already installed.

Ice studio then very slow to start, says toolchain broken click here....then complains that python 3.5 or better is needed.

**Comment by cavearr** [comment] 2020-04-10 05:35
We are working on this issue, the problem is that Icestudio don't recognize your python path. 

Don't worry we are improve this with a panel to manually configure your python path. 


De: "Dave Spring" <notifications@github.com> 
Para: "FPGAwars/icestudio" <icestudio@noreply.github.com> 
CC: "Carlos" <carlos@magnitude.es>, "Comment" <comment@noreply.github.com> 
Enviados: Jueves, 9 de Abril 2020 21:38:21 
Asunto: Re: [FPGAwars/icestudio] Windows with Visual Studio Install Issues (#368) 





uninstall ice studio. uninstall python 2.7 (left 3.8.2 installed) 
download nightly win 64 
install says python 3.8.2 will be installed. despite already installed. 

Ice studio then very slow to start, says toolchain broken click here....then complains that python 3.5 or better is needed.

**Comment by Obijuan** [comment] 2021-06-29 14:23
It would be great if you could test the latest stable version: 0.6.0-rc2:

https://github.com/FPGAwars/icestudio/releases/tag/v0.6.0-rc2

to check if the bug has been fixed or not. Any feedback is very welcome. Thanks! :-)

**Comment by Obijuan** [comment] 2022-05-02 19:05
As no feedback given since Jun29-2021, I assume that this bugs has been fixed in the latest icestudio versions.
Thanks for the feedback

**Closed by Obijuan** 2022-05-02 19:05 UTC
Labels: bug, Platform specific, pending feedback
