### ISSUE TITLE
Parameter in the block is allways 0 

### ISSUE THREAD

**Issue by benitoss** [FPGAwars/icestudio#550] opened 2021-11-10 15:13 UTC
In the last nightly version 0.7.1w202110210410 there is a bug in the parameter part.
When you synthetize the code, the external parameter always takes the value 0
It happens in HX8K, UP5K, and ECP5 boards (I suppose in all boards)
I am using the apio version 0.7.7

**Comment by Obijuan** [comment] 2021-11-10 17:16
It wouled be great if you could provide an icestudio file with a minimal circuit with that bug. It is for undertanding better the bug and testing it in other boards.

**Comment by benitoss** [comment] 2021-11-10 19:36
In this example file 
[tm1638_led_key__test.zip](https://github.com/FPGAwars/icestudio/files/7515462/tm1638_led_key__test.zip)

IceStudio synthetizes but I got this error
main.v:3498: Warning: Range [-1:-1] select out of bounds on signal `\divcounter': Setting 1 LSB bits to undef.
Please, Could you explain why I got this error ???

Thanks

**Comment by jojo535275** [comment] 2021-11-13 18:03
Ola Fernando,

- i tryed your file wit my icestudio 0.7.1w202109100309  with apio 0.7.6, and also got the exact same warning.
- it is a warning not an error so maybe  we can just ignore it !?
- i created the smallest ice file(see joined file) where this warning appears:

[range warning.zip](https://github.com/FPGAwars/icestudio/files/7532467/range.warning.zip)
![range warning](https://user-images.githubusercontent.com/65027759/141653260-1e59aa6f-19d0-45d9-9ed4-3b27526d36e4.JPG)
Yosis gives the warning in command output:
  yosys -p "synth_ecp5 -json hardware.json" -q main.v
  main.v:30: Warning: Range [-1:-1] select out of bounds on signal `\pres': 

and if we export the verilog code with the corresponding icestudio function we have

![icestuio verilog export](https://user-images.githubusercontent.com/65027759/141653325-84c5d1dd-8630-4ffd-8b54-7f2a28967938.JPG)
- So, the problem is that icestudio affects (at line 25 ) by default 0 as value for the external parameter (above a block). 
and at line 30 & 31  we have a N-1 (0-1) and yosis  sees that as potential problem.  It is looking for errors at each individual module/block, module by module.
-As we are quite often using N-1 in our blocks verilog code, if we want to decrease the number of yosis warnings we may change the default value given for a parameter in a block (eg: to 1 instead of 0 ).

**Comment by benitoss** [comment] 2021-11-15 05:04
I think the warning is because the internal parameter N in the instance  module is 0 and when we call the instance we set the parameter with a value greater than 1 , so finally the Bitfile generated perfectly  works. It is only a warning. 
Thanks fort checking it

**Comment by cavearr** [comment] 2021-11-24 21:48
Closing the issue, reopen if it is necesary.

**Closed by cavearr** 2021-11-24 21:48 UTC
