### ISSUE TITLE
problem uploading to upduino 3.1

### ISSUE THREAD

**Issue by itsme200** [FPGAwars/icestudio#686] opened 2023-03-18 14:15 UTC
So i bought an upduino 3.1 for a school project. I installed Ice studio and selected the board. I checked that the version was 0.10.0 since only this one supports it. At first I was getting the ftdi_usb_get_strings failed: -4 (libusb_open() failed) error. after that I installed apio manually since that could of have been an issue. And after that the apio system --lsftdi outputed that one device was found and the name was single rs232. So that was sorted. I enabled the drivers and after trying to upload again it only outputed the Upduino 3.1 not connected error. I have tried multiple fixes but none of them worked. Any help would be apreciated.
![1  problem](https://user-images.githubusercontent.com/105128509/226111379-f58325c9-c022-4922-abbb-294185c4f637.png)
![2  problem](https://user-images.githubusercontent.com/105128509/226111496-bf02ce5b-1002-4781-bd1f-3136a7a5114f.png)

**Comment by vr2045** [comment] 2023-05-17 01:50
Looks like the FTDI EEPROM got blown away somehow so you're seeing this as a 'single rs232'. This should show up as a UPduino 3.0/3.1 so icestudio can recognize it.
Please use the script [here ](https://github.com/tinyvision-ai-inc/UPduino-v3.0/tree/master/Board/EEPROM) to reinitialize the EEPROM then unplug/replug the board. Should then get recognized by icestudio.

**Comment by dee2dee3** [comment] 2023-12-25 01:03
im having a similar problem where i cant upload to my upduino because Icestudio cant seem to recognize it, would this solution work for me? if so how do I do it

**Comment by cavearr** [comment] 2024-02-05 18:35
Hi !! yo fix the problem? i'll keep open the issue some more days awaiting for your response and if not i'm closing it.

The problem is more related to upduido than icestudio.

Reopen when you want if you encountered it  closed.

**Comment by vr2045** [comment] 2024-02-06 01:58
Hello,
Please stop by the tinyVision.ai discord server so we can help you:
https://discord.gg/3qbXujE
Agreed, this is not an icestudio issue and should be closed.

**Closed** 2024-02-06 19:51 UTC
Labels: waiting for feedback
