### ISSUE TITLE
md.cpython-39-darwin.so cannot be opened on MacOS fresh install

### ISSUE THREAD

**Issue by fxframes** [FPGAwars/icestudio#730] opened 2024-04-14 14:20 UTC
Not much to add, Icestudio installs fine on macOS Sonoma 14.4.1 but as soon as it's opened it throws this error.
I found the file and tried to do the MacOS right-click thing and open it "manually" using Icestudio but to no avail.
Thanks for any insights.

![Screenshot 2024-04-14 at 15 16 31](https://github.com/FPGAwars/icestudio/assets/68516637/284f950b-af43-4f01-9541-aa5eef5d6907)

**Comment by cavearr** [comment] 2024-04-14 15:18
What version of Icestudio are you using?

**Comment by fxframes** [comment] 2024-04-14 16:26
Thanks for the quick reply.
The file I downloaded from icestudio.io is named icestudio-0.11.0-rc2-osx64.dmg.
I'm on an M1 Mac by the way.

**Comment by cavearr** [comment] 2024-04-14 16:51
try downloading the last wip from https://downloads.icestudio.io

Our wips are very stable and more up to date that our stable versions that are used by some universities that need very stability.

Tell me if this works!

**Comment by fxframes** [comment] 2024-04-15 07:42
Thanks, I tried the two latest MacOS ARM versions available but both give me an error.

<img width="266" alt="Screenshot 2024-04-15 at 08 40 49" src="https://github.com/FPGAwars/icestudio/assets/68516637/1f089165-008b-4401-9661-b45f16327ef9">

**Comment by cavearr** [comment] 2024-04-15 22:01
Give me a couple of days to fix it, there are some problem with osx signature

**Comment by fxframes** [comment] 2024-04-16 07:27
Thank you for your support. =)

**Comment by setrar** [comment] 2024-04-20 08:15
I uninstalled the homebrew version and I was able to install this version [icestudio-0.11.3w202402070902-OSXARM 64.dmg](https://api.github.com/repos/FPGAwars/icestudio/actions/artifacts/1364134182/zip)

![image](https://github.com/FPGAwars/icestudio/assets/123704/0345b900-5dac-4dd3-85e5-7e81bbb51791)

**Comment by cavearr** [comment] 2024-06-06 06:26
Hello everyone! At the moment the issue seems to be fixed, now packages are automatically signed in github CI actions and the user only needs to accept the unknown developer in the security check in the security section of the settings panel (as it usually appears with other apps).

I'm working on a dmg with less friction, but at the moment it works relatively comfortably.

I'll be closing the thread and reopening it in the near future to let you know about the new improvements to damage output.

Greetings and thank you very much for using Icestudio!

**Comment by grijspetje** [comment] 2024-06-06 07:37
I just checked and the last update is from 5th of june. Is version 0.11.3w202406050906 the last version because  this version has the python install problem.

kind regards,

Peter

**Comment by cavearr** [comment] 2024-06-06 08:38
Hi @grijspetje !, how do you install python in your system? i can't reproduce. the python problem and i think could be a python environment problem that i want to fix or patch.

For the screenshot i view the problem appears when install the toolchain ,isn't it?

But in my OSX when try to install the toolchain appears the next dialog, asking for admin user and password:

<img width="932" alt="Captura de pantalla 2024-06-06 a las 10 34 12" src="https://github.com/FPGAwars/icestudio/assets/6904865/edc66fbf-c9ef-4614-b787-cdc0524e0287">

In your case don't appear this? if not appear i'll need to check why, could be possible that i have installed some package that is not standar (development package).

Thanks for your feedback!

**Comment by grijspetje** [comment] 2024-06-06 14:00
Carlos,

I send you some screenshots to show yoou what I encounder.

Downloaded icestudio-0.11.3w202406050906-osxarm64 and started up:

￼

download the latest tools. 

No problem

Installing drivers:

takes a long time

￼

and now it seems to be ok!

I dont know what has changed.

kind

Regards,

Peter

**Comment by cavearr** [comment] 2024-06-06 14:37
Hello Peter! I don't know what could happen, I was never able to reproduce it, it could be some version overlap in your installation, I really don't know.

If it already works and looks good to you, I'll close the issue and if it appears again, reopen it, okay?

Thanks again for your patience and your comments!

**Closed by cavearr** 2024-06-06 14:37 UTC

**Comment by grijspetje** [comment] 2024-06-06 17:27
OkMet vriendelijk groeten,Peter van den BosVerstuurd vanaf mijn iPadOp 6 jun 2024 om 16:38 heeft Carlos Venegas Arrabé ***@***.***> het volgende geschreven:﻿
Hello Peter! I don't know what could happen, I was never able to reproduce it, it could be some version overlap in your installation, I really don't know.
If it already works and looks good to you, I'll close the issue and if it appears again, reopen it, okay?
Thanks again for your patience and your comments!
